### ISSUE TITLE
Options method getting called twice

### ISSUE THREAD

**Issue by jcbvm** [ember-cli/ember-ajax#122]
The method `raw` in het `ajax-request` mixin is calling `this.options`, while `request` is already calling this method, seems unneccessary to me? The reason I'm asking is because I'm overriding the `options` method in my custom addon, which will result is some wrong behaviour because its being called twice (second time with an already modified options object from the first time).

Can't `raw` simply get the `hash` calculated within the `request` method?

**Comment by alexlafroscia** [comment]
Hey @jcbvm, thanks for the report.  I'm pretty sure that [this line](https://github.com/ember-cli/ember-ajax/blob/d8b1c299fe03292640c51b9455ce75807c7a8544/addon/mixins/ajax-request.js#L204) is the reason for getting the options twice, so that the debugging tools can get the full URL and `type`.  That does feel like a pretty lame reason though, and I'm sorry the current behavior is messing with your override.

Was there another reason @taras? I'm thinking that we could maybe change the `raw` method to something like `_raw`, then make a new `raw` method that just gets the options and calls `_raw`, then change `request` to do the same (get the options and then call `_raw`).

Thoughts?
