### ISSUE TITLE
End of input when no JSON is returned with 200 OK from server.

### ISSUE THREAD

**Issue by constantm** [ember-cli/ember-ajax#14]
Awesome addon! However, when used with Rails and response is set with the following:

```ruby
respond_to do |format|
  format.json { head :ok }
end
```

You get an error:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at jQuery.parseJSON (http://localhost:4200/assets/vendor.js:7736:14)
    at ajaxConvert (http://localhost:4200/assets/vendor.js:8013:19)
    at done (http://localhost:4200/assets/vendor.js:8429:15)
    at XMLHttpRequest.<anonymous> (http://localhost:4200/assets/vendor.js:8819:9)
```

However, when you add some actual JSON content to the response, it seems to work fine.

**Comment by mike183** [comment]
I ran into this issue yesterday. The reason you are seeing an error is because ember-ajax expects a JSON response by default ([see this line](https://github.com/ember-cli/ember-ajax/blob/0c6b9373c4c842fe70060ae5e1504bb37f55e0ec/addon/services/ajax.js#L146)), as a result is attempting to parse the response as JSON.

If you're not returning a JSON response, you should update the `dataType` attribute to something more appropriate. For possible values, see jQuery's [$.ajax() docs](http://api.jquery.com/jquery.ajax/) for `dataType`.

e.g.

```js
this.get("ajax").request("/some/request/url/", {
  dataType: "text"
});
```

**Comment by jcbvm** [comment]
I think the line you mentioned should not be included in this lib, the jQuery auto detection of dataType is fine by default.

**Comment by alexlafroscia** [comment]
Considering that @mike183 posted the solution to this issue, I'm going to close it out.
