### ISSUE TITLE
Drop AJAX error detection helpers

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-ajax#177]
I feel like the error detection functions that we provide aren't all that useful.  Specifically:
- Functions should generally take one kind of input and return one kind of output.  We take either an `AjaxError` instance _or_ a number and try to verify that it's describing some kind of error. While useful, I think this is kind of confusing behavior.
- People really can't (or shouldn't) have code where the argument is some variable that could be either an error object or a number; they must know ahead of time whether it's a number or error object and could just check it directly
- If they are using it with only one argument type in mind, then they should just do a number comparison, or an `instanceof` check, themselves.  Preferably the latter, since our descriptive error classes remove the need checking the status code directly.

If we were to remove them in `v3.0.0`, then for the time being we would deprecate the error checkers, and then remove them entirely in `v3.0.0`.

**Comment by jherdman** [comment]
👍

**Comment by sandstrom** [comment]
Somewhat related, it would be neat if it was easy to either `reopen` ajax errors, or provide a custom error base class.

**Comment by alexlafroscia** [comment]
@sandstrom what's the use case on that?

**Comment by sandstrom** [comment]
Our server responses contain a bunch of useful metadata, in a specific JSON format.

Instead of having to dig out details, e.g. `myError.payload.envelope.meta.request_id` I'd like to add a property to the error class such that `myError.requestId`would exist.

An alternative to providing a custom error class would be the ability to modify/setup the error instance after it's created. I know there is `parseErrorResponse` and `normalizeErrorResponse` but none of them allow setting up properties on the error instance itself.

**Comment by alexlafroscia** [comment]
Huh, interesting. Definitely a reason to do this.

Right now, we use a regular JS class for the errors. If we adopted Ember classes, you'd be able to reopen them; would that fit your use case?

Also, I'd love to take this discussion to a new issue. Would you make one and explain the use case (coping you comment here is fine) @sandstrom?

**Comment by sandstrom** [comment]
@alexlafroscia Done! https://github.com/ember-cli/ember-ajax/issues/292

**Comment by alexlafroscia** [comment]
I've changed my mind on this and would rather just keep them around.
