### ISSUE TITLE
RequestURL.get fails with this.url.match is not a function 

### ISSUE THREAD

**Issue by epchristi** [ember-cli/ember-ajax#179]
I am trying to upgrade an existing ember project to the latest version. I pulled in ember-ajax version 2.5.2.
The code has a call toe _emberAjax['default'])({ type: 'POST', dataType: 'json', url: 'api/endpoint' });

The call stack fails in RequestURL.get (url-helpers) with this.url.match is not a function.

Does ember-ajax depend on another library that isn't part of the ember install?

**Comment by epchristi** [comment]
Sorry, the code was take from chrome's debugger. The actual code is:
return ajax({
			type: 'POST',
			dataType: 'json',
			url: '<endpoint>',
			data: data
		});

**Comment by epchristi** [comment]
If I change the code in url-helpers.js, in the function get:, with the key: 'isComplete', to do this.url.url.match, then the method works as expected.

Is this a bug? Or do I need to change the way the ajax calls are made for the new version?

**Comment by alexlafroscia** [comment]
I need to see more of your code. What is `ajax` in your example?

**Comment by epchristi** [comment]
import ajax from 'ember-ajax';

**Comment by epchristi** [comment]
I think I need to change the format of the ajax requests.

**Comment by alexlafroscia** [comment]
The `request` function takes two parameters but you're only passing one.

https://github.com/ember-cli/ember-ajax/blob/3ebfef02d37614c7f09d0d7d92ba741a47866664/addon/mixins/ajax-request.js#L197

**Comment by alexlafroscia** [comment]
I'm going to guess that that's the problem.  The first param should be a string, which gets passed to the `RequestURL` class [here](https://github.com/ember-cli/ember-ajax/blob/3ebfef02d37614c7f09d0d7d92ba741a47866664/addon/mixins/ajax-request.js#L451).  That then becomes the `url` property of an instance of that class.  The string would have a `match` method but, because you're passing an object as the first parameter, there is no `match` method and you're getting that error.

If you changed your code to be this, instead:

```js
return ajax('/api/v1/endpoint', {
  type: 'POST',
  dataType: 'json',
  data: data
});
```

I'll bet your issue will be solved.
