### ISSUE TITLE
Upload file using "FormData"

### ISSUE THREAD

**Issue by prakashraman** [ember-cli/ember-ajax#212]
Really like the ember plugin. Using it pretty much everywhere in the application.

I wanted to know if I could use "FormData" to upload a file?

**Comment by alexlafroscia** [comment]
Did you try something and have it not work? It seems like `$.ajax` supports this, based on this StackOverflow post:

http://stackoverflow.com/a/8244082/2250435

**Comment by prakashraman** [comment]
Hi Alex.

No I have not tried it with "ember-ajax". Although, it does work with $.ajax (jQuery's implementation).

**Comment by prakashraman** [comment]
Shall be giving it a shot in a couple of days anyway - shall update this thread with findings

**Comment by alexlafroscia** [comment]
Alright. `ember-ajax` is just a wrapper for `$.ajax` so if it works there, it should work here.

I'm going to close this issue since there isn't a problem at this time. If you try it out and find that something isn't working, please re-open it.  Either way, I'd love to hear your feedback on how it goes for you!

**Comment by prakashraman** [comment]
Oh brilliant! Then it should work perfect. Yes, please, do close it. I shall let you know how it goes.

Thanks for this - love the plugin!

**Comment by alexlafroscia** [comment]
> Thanks for this - love the plugin!

Thanks for saying that! You tend to only hear about when things go wrong on Github -- it's really nice to hear positive feedback sometimes!
