### ISSUE TITLE
Request with the same url as namespace produces unwanted results

### ISSUE THREAD

**Issue by mongeta** [ember-cli/ember-ajax#216]
When the url from de requests is exactly as the namespace, ember-ajax replaces it with the current model name.

ember-ajax: 2.5.3
ember: 2.10.1
ember-data: 2.10.0

```
...
 export default AjaxService.extend({
 session: Ember.inject.service(),
  host: ENV.APP.host,
  namespace: 'provisiones',
...
```

`this.get('ajax').request('provisiones', {
            method: 'GET',
            data: {
                options: 'resume'
            }
        })`

The url is: http://127.0.0.1:4200/abonos/new

The resulted network call is this: http://127.0.0.1:4200/abonos/provisiones?options=resume

When it should be: http://127.0.0.1:4200/provisiones/provisiones?options=resume

If I change the ajax request with this:

`        this.get('ajax').request('provisionez', {
            method: 'GET',
            data: {
                options: 'resume'
            }
        })
`

The resulted network call is: http://127.0.0.1:3000/provisiones/provisionez?options=resume

thanks,

**Comment by alexlafroscia** [comment]
Hey, I tried to reproduce this but was unable to. Can you please PR a failing test case (preferred) or send me either a link to a repo or an [Ember Twiddle](https://ember-twiddle.com) that shows the issue? That would help me get to the bottom of this.

**Comment by Charizard** [comment]
@alexlafroscia I am experiencing the same problem.

I have the namespace as `/admin` and the host as `http://localhost:3002` in the ajax service. Now, when I try to do `get(this, 'ajax').request('/admin_users/xyz')`, the request made is `http://localhost:3001/admin_users/xyz` where as the expected call is `http://localhost:3002/admin/admin_users/xyz`.

Specifically, the problem is in [this](https://github.com/ember-cli/ember-ajax/blob/master/addon/mixins/ajax-request.js#L488) comparison. I think to identify if the URL is already constructed by ember-data there needs to be a better way.

**Comment by alexlafroscia** [comment]
Cool, thank you for the additional information @Charizard. That's really useful!

All of the URL building right now is a bit... wonky. I'll look into trying to make that more reliable.

**Comment by Charizard** [comment]
@alexlafroscia Do you have any other ideas for detecting if the URL was already build?
