### ISSUE TITLE
CORS Request

### ISSUE THREAD

**Issue by amaianazabal** [ember-cli/ember-ajax#284]
Hi, how it is possible to make a CROS request? or send **jsonp** for generate the callback function?
I'm new with ember-ajax, but I don't find in the doc any reference to this. Thanks!

**Comment by alexlafroscia** [comment]
Do you mean CORS? And `jsonp`, yes, we support it.

By and large, the API for `ember-ajax` and regular `$.ajax` is the same, so that should help you with the CORS bit, probably. It should just be a matter of setting some headers, and you can either do that on a per-request basis or by setting the `headers` property on the `ajax` service.

There is an example of using JSONP in the test suite for reference:
https://github.com/ember-cli/ember-ajax/blob/2aba19ed7c9f1771994895237c7b20ca52165871/tests/unit/mixins/ajax-request-test.js#L855

**Comment by sandstrom** [comment]
@amaianazabal CORS is primarily configured on the server-side. I've you've done the server setup correctly things should just start to work on the client side (no changes to ember-ajax needed).

If you are using a server-side framework, google `{name-of-framework} + CORS`.

https://enable-cors.org/server.html

**Comment by amaianazabal** [comment]
Thanks, It works very well..
