### ISSUE TITLE
Customizable Error Classes

### ISSUE THREAD

**Issue by sandstrom** [ember-cli/ember-ajax#292]
Our server responses (for errors) contain a bunch of useful metadata, in a specific JSON format.

```js
{
  "envelope": {
    "request_id": "xyz123", // unique id, to correlate server-side and client-side logs
    "helpful": "Helpful description, written for a human!",
    "machine": "machine-error-code"
  }
}
```

Instead of having to dig out details, e.g. `myError.payload.envelope.request_id` we'd like to add a property to the error class such that `myError.requestIdwould` exist.

One solution may be reopenable error classes, but I don't know if this is possible. Another could be to set the error class on the mixin/service. In the latter case, we could extend similar to how Ember Data [does it](https://github.com/emberjs/data/pull/3586).

Happy to hear others thoughts on this! ⛵️ 

***

An alternative to providing a custom error class would be the ability to modify/setup the error instance after it's created. I know there is `parseErrorResponse` and `normalizeErrorResponse` but none of them allow setting up properties on the error instance itself.

**Comment by alexlafroscia** [comment]
Hmm. This is an interesting use case, and I think it would be a powerful tool.

Now that `normalizeErrorResponse` is a no-op, maybe we should move _all_ of the error handling into a method that can be overwritten and customized? If the user wants to do extend the default behavior, they can call `super`, and whatever they return from the model becomes what the promise is rejected with?

I think that would allow you do implement your custom errors, because you could get the response from calling `super` and extend it, or just do your own error handling without invoking the default classes. I'd love to hear your feedback to this idea, or maybe your thoughts on what an API for achieving this would look like @sandstrom.

**Comment by catz** [comment]
+1 currently, I have no idea on how to track 449 status for example or easily extract json response.

`if(error.errors[0] && error.errors[0].status === '449') {`

this looks ugly (

**Comment by alexlafroscia** [comment]
I'm going to close this, as there's already a means for doing this if you really want to (although it isn't super pretty)

1. Create your own custom Error class(es?) by extending from the build-in ones
2. Override the `_createCorrectError` method on your `ajax` service, which takes in a set of request meta-data (status, headers, payload, etc) and returns an `AjaxError` object (or a subclass of it).

If you want to use some other kind of custom class, as long as you extend from `AjaxError` or one of the subclasses, it should "just work".

**Comment by sandstrom** [comment]
@alexlafroscia Totally fine, we've already moved over to ember-fetch 😄

**Comment by alexlafroscia** [comment]
That's what I suggest most people do then they can. I think `fetch` is easier to understand and is the modern way of doing things. Unfortunately some people are relying on `jQuery` features so they can't switch over, so this addon is going to stick around.
