### ISSUE TITLE
_buildURL('assets/foo.json') adds leading slash?

### ISSUE THREAD

**Issue by nag5000** [ember-cli/ember-ajax#331]
```js
this._buildURL('assets/foo.json') === '/assets/foo.json'
```

Relative URL to the current path becomes relative URL based on the document root.

**Comment by alexlafroscia** [comment]
Ugh. Thanks for reporting. The URL building is kind of a mess...

I'll try to get to this soon, but as always, PRs are very welcome!

**Comment by baljeet03** [comment]
I was going to make PR on this one. So I had a few doubt which I just wanted to clarify before making a PR :). 
Few cases need to be considered - 
1) namespace - api, url - admin => api/admin
2) namespace - /api, url - admin => /api/admin.

Am I in right path?

**Comment by alexlafroscia** [comment]
This gets really tricky, IMO. I have always felt like defining `/api` or `api` for the namespace should result in the same thing. I think that constructing a relative API is just a recipe for code that can be ambiguous, but at the same time, I can't really push that perspective onto other through the API here...

One problem with `namespace` with/without a leading `/` is behavior when mixed with setting `host`

If you have `{ host: 'foo.com', namespace: 'api' }` and `{ host: 'foo.com', namespace: '/api' }`... Do they produce the same URL? 

I would think they _do_... but that is different behavior than what you proposed before, where the `/` _does_ matter.

I have also ran into a problem where some people include a leading URL segment in the `host` field... what happens when both that _and_ a `namespace` are present?

All hard questions, none of which I have great answers to. All of that ambiguity is what has historically made the URL-building code way more buggy than I would like.

If you want to put together a PR as a starting point, I'm happy to work together on ironing out these questions!

**Comment by baljeet03** [comment]
#365

**Comment by alexlafroscia** [comment]
Closed by #365
