### ISSUE TITLE
Storing all the endpoint URLs at one place

### ISSUE THREAD

**Issue by rinoldsimon** [ember-cli/ember-ajax#401]
my ember app does some of the API calls using `ember-ajax` addon.
There is a situation where `same endpoints` will be used at multiple places.
If endpoints url changes in the server, we need to update the endpoints at multiple places in ember. That is inconvenient.

So i created a file under `app/api.js` where we store all the endpoints URLS
```
export default {
  roles: '/filters/roles',
  email_change: '/email/change`
}
```
then we used it inside our `component` as,
```
...
import endpoints from '../../api';
...

export default Component.extend({
  ajax: Ember.inject.service(),
  actions: {  
    ...
    this.get('ajax').request(endpoints.roles);
    ...
  }
})
```
Everything works fine.
What i need is,
1) Is this the right way of storing all the endpoint in `app/api.js` file ?
2) Now i need to import `import endpoints from '../../api';` in every component and controller whichever place i use `ember-ajax` request. Is it possible to import api.js at a common place and use it directly in `component` by just calling `endpoints.roles` ?

**Comment by rinoldsimon** [comment]
that makes sense.

Is there any idea to add it as a `future request` to add it as an additional feature in `ember-ajax` addon ?
Something like defining all the endpoints at `services/ajax.js` file 
```
export default AjaxService.extend({
  host: ...,
  namespace: ...,
  endpoints: {
    role: 'filters/roles',
    ...
  }
})
```
and using it as `this.ajax.request(endpoints.roles);

so this might avoid the redundancy

**Comment by alexlafroscia** [comment]
Probably not -- the code example you're showing there can be achieved just by making `endpoints` a global variable, and that's both

1. Not recommended, as the larger JS community doesn't like globals
2. Totally possible to achieve right now without adding a feature for it

If you create the service exactly as you showed above, the "usage" is just 

```
this.ajax.request(this.ajax.endpoints.roles)
```

which is almost the same, but makes it clear where `endpoints` comes from rather than them being a global variable defined somewhere.
