### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by jonathansamines** [ember-cli/ember-ajax#423]
I am just updating an existing ember project, and noticed a deprecation warning when using latest on both v3 and v4 of this package. Is this package no longer maintained? If that is the case, is there an existing addon you would recommend instead?

Thanks for your time!

![image](https://user-images.githubusercontent.com/1268268/49554895-5ac57000-f8c3-11e8-8290-bd9c00197e69.png)

**Comment by jonathansamines** [comment]
@jherdman Thanks for your response. Our project is working great, however we noticed the deprecation warning and we wanted to know if this project was no longer maintaned. Since that is not the case, can I ask, why are those versions (including latest) deprecated?

**Comment by jherdman** [comment]
I'm not familiar with any deprecation in the most recent version. Would you mind sharing the message?

**Comment by alexlafroscia** [comment]
Hm.. So, I used a deprecation warning on `4.0.0` to call out some vital information for those upgrading from a previous version to `4.0.0`, directing folks to the release notes. I did that because of some breaking changes that slipped out in a non-major release and the way that we went about fixing the issue.

I can (and will) release a `4.0.1` this weekend that matches `4.0.0` from a feature perspective, so that new users aren't faced with that deprecation warning.

Thanks for bring this to my attention!

**Comment by mike-north** [comment]
@alexlafroscia You might want to cut that 4.0.1 release soon. Dependency-checking tooling currently sees this package as having its most recent release as deprecated, which could be (reasonably) interpreted as the package being deprecated as a whole.

One example of this kind of thing is automated issues like this
https://github.com/typed-ember/ember-cli-typescript-blueprints/issues/42

**Comment by mike-north** [comment]
It's not just the dependency bots, it's NPM that things `ember-ajax` is entirely (all versions) deprecated.

<img width="1342" alt="screen shot 2018-12-09 at 2 51 35 pm" src="https://user-images.githubusercontent.com/558005/49704019-028fb600-fbc2-11e8-9764-5baa34a768c6.png">

**Comment by alexlafroscia** [comment]
`4.0.1` published just now!

Thanks for that additional context @mike-north; I appreciate the larger context around the side-affects of using a deprecation warning the way I did.
