### ISSUE TITLE
Warn user if improperly calling `.get()` on AjaxService

### ISSUE THREAD

**Issue by nucleartide** [ember-cli/ember-ajax#51]
For a couple of minutes, I was wondering why this didn't work:

```javascript
this.get('ajax').get('/someResource', { data: /* ... */ });
```

...before realizing that `.get()` is from `Ember.Object`. D:

Do you think it'd be a good idea to perhaps log an error if someone is using that method incorrectly? If so, maybe we could check if the second argument is an object, or if the first arg has a leading slash or something.

**Comment by alexlafroscia** [comment]
I've run into that same problem myself, but I'm not sure how exactly to pull that off since technically `.get` _is_ a valid API, just not for making requests.

We could look at overriding the `.get` method, checking against a whitelist of valid properties and sending that error if it doesn't match.  However, then we have to keep that list up to date and I'm not sure it would play too nicely with the fact that we use an ES6 class under the hood.... So my inclination is that that wouldn't be a good solution.

@taras do you have any suggestions?  As much as I think this would be a great thing to have, I'm just not sure how we would do it since `.get` is Ember's API

**Comment by taras** [comment]
@alexlafroscia we could overload `get` method and check for how many arguments are passed. If we detect that the user is using get as GET then throw a warning into the console. We won't be able to check in situation when someone does `this.get('/someResource')` but it's better than nothing. 

What do you think?

**Comment by alexlafroscia** [comment]
Yeah, that seems like a good compromise.  We could even try to catch instances where the parameter to `.get` starts with a `/` to _try_ catching that use case as well.

I'm wondering how implementation would go, since the ES6 class is converted into a Mixin and then applied to the Service that way.  I'll mess around with it tonight or tomorrow and see what I can do.
