### ISSUE TITLE
Serializing errors

### ISSUE THREAD

**Issue by kmiyashiro** [ember-cli/ember-ajax#66]
If an error response returns a JSON payload, the ember-ajax error only returns `[object Object]` for the message. It would be useful to be able to customize the way it handles error payloads.

**Comment by alexlafroscia** [comment]
Which version are you using?

**Comment by kmiyashiro** [comment]
0.7.1

**Comment by alexlafroscia** [comment]
I think that's something that has been addressed since that release, but is available in the current beta versions; see [this commit](https://github.com/ember-cli/ember-ajax/commit/2a08b39495d89fce9d2bec9cc534cc7ca9d64512).  Please give the current beta a shot and let me know if that handles things for you.

For the meantime, I'm going to close this issue.  We can re-open it if that doesn't take care of the problem.
