### ISSUE TITLE
Send "Content-Type": "application/json; charset=utf-8" by default

### ISSUE THREAD

**Issue by nucleartide** [ember-cli/ember-ajax#79]
Hey folks, first of all great job with the library :)

So I notice that ember-ajax sends data with a content type of `application/x-www-form-urlencoded` by default. Since sending JSON is so common, would you think it's a good idea for `application/json` to be the default content type instead? (Like in [superagent](https://visionmedia.github.io/superagent/#post-/-put-requests).)

For example, instead of this:

```js
this.get('ajax').post(url, {
  contentType: 'application/json; charset=utf-8',
  data: JSON.stringify({
    hello: 'world',
    foo: 'bar'
  })
}
```

You could do something like this:

```js
this.get('ajax').post(url, {
  data: {
    hello: 'world',
    foo: 'bar'
  }
})
```

I'm thinking it would just cut down on some boilerplate. What do you think?

**Comment by alexlafroscia** [comment]
I'm absolutely in favor of doing this.  It might break some people's default behavior though, if they're relying on the fact that the default `contentType` is the same as what `jQuery` uses.  I agree completely that `application/json` is a more sensible default, though.

If you'd like to submit a PR for this in the next day or so (with a test) then I'd like to pull that in before the 2.0 release, which has some other breaking changes.  Because of the breaking nature of the change, though, if it doesn't make it into 2.0 (which we're planning to make official _very_ soon) then it would have to wait until 3.0.

**Comment by timkendall** [comment]
Just ran into this myself. Would be nice if we had a way to just set this when we extend the `ajax` service.

**Comment by cqcsobreyra** [comment]
Just wanted to share an idea for a quick dirty fix how to achieve default options for those who might find it useful. In the ajax service you could do something like

```
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

export default AjaxService.extend({
    configuredRequest(url, options){
        var defaultOptions = {
            cache: false,
            contentType: 'application/json; charset=UTF-8',
            processData: false
        }

        if (options) {
            $.extend(defaultOptions, options);
        }
        this.request(url, options);
    }
});

```
And then just call this.get('ajax').configuredRequest('/yoururl', yourOptions);

**Comment by zeiv** [comment]
I was struggling for several hours to get my API to communicate with ember-ajax properly before realizing the ajax request wasn't formatted in JSON.  The above would be _really_ nice, or at the very least **put something in the documentation** explaining that the default content-type is urlencoded and what you need to do to get ember-ajax to send JSON requests.

**Comment by alexlafroscia** [comment]
Hey all, so after #116 gets pulled in, the solution (for the time being) is to set a `contentType` property on the service to change the default value to whatever you want.  This way you can provide `application/json` at the service level instead of needing it on every request.

We totally agree that making the default `json` makes more sense, but feel that changing a default value like that constitutes a breaking change.  We'll be making that for the next major release, but just aren't ready to do so yet.  Hopefully that PR is a good enough compromise for the time being.

**Comment by alexlafroscia** [comment]
@nucleartide if that feels like a good enough solution, I'd love to consider the issue closed.

**Comment by nucleartide** [comment]
Yep, just tried it out - looks great! @cqcsobreyra's idea is good, here's the custom `AjaxService` I made to support my original use case:

```
import AjaxService from 'ember-ajax/services/ajax'

export default AjaxService.extend({
  contentType: 'application/json; charset=utf-8',

  options() {
    const result = this._super(...arguments)
    if (result.contentType === this.get('contentType')) {
      result.data = JSON.stringify(result.data)
    }
    return result
  }
})
```

Usage:

```
// import stuff
import Ember from 'ember'
const {
  inject: { service }
}

// inject service
ajax: service('custom-ajax')

// use
this.get('ajax').post('/helloworld', {
  data: {
    hello: 'world'
  }
})
```

**Comment by alexlafroscia** [comment]
>  @cqcsobreyra's idea is good, here's the custom AjaxService I made to support my original use case:

You mean allowing a way to provide default values for arbitrary `options` values?  I think the way I'd recommend that would be doing that be overriding `options` and calling `_super`, like the above example.
