### ISSUE TITLE
Keep CHANGELOG.md updated

### ISSUE THREAD

**Issue by urbany** [ember-cli/ember-ajax#97]
Hi, would it be possible to update CHANGELOG.md with each release? I know it seems like waste of time, but it really helps when all the thousands of users of this awesome library are deciding on upgrading :)

Thanks a lot in in advance

**Comment by taras** [comment]
Yes, this is definitely something that we're looking to add in short term. Thank you for the suggestion.

**Comment by urbany** [comment]
Awesome. Thanks for the quick reply @taras :)

**Comment by alexlafroscia** [comment]
Hey @urbany! Thanks for the request.  I'm trying to come up with a good way to keep the `CHANGELOG` up to date.  For the last release, it's part of the notes associated with the Git tag; I'll be sure to update the in-repo version next time as well!  If you don't mind, since this isn't really immediately actionable, I'm going to close the issue here.

**Comment by urbany** [comment]
Thanks @alexlafroscia that would be perfect!
