### ISSUE TITLE
Error in connection with ember-cli-mirage

### ISSUE THREAD

**Issue by spruce** [ember-cli/ember-ajax#98]
I don't really know where it comes from. But I have an issue with mirage and ember-ajax

My code is as follows:

```js
//some controller
this.get('ajax').post('/api/resendEmail', {
        data: {
          email: email
        }
      }).then(function(/*data*/) {
        //yay
      }).catch(function(reason) {
        console.log(reason); // get's called
...
```

```js
this.post('/resendEmail', function(db, request) { 
    return new Response(200, {}, "not verified"); // api is fix
  });
```
This should nicely call the success callback but instead it calls the catch with the following reason stack:
```
SyntaxError: Unexpected token o
    at Object.parse (native)
    at jQuery.parseJSON (http://localhost:4200/assets/vendor.js:7782:14)
    at ajaxConvert (http://localhost:4200/assets/vendor.js:8059:19)
    at done (http://localhost:4200/assets/vendor.js:8475:15)
    at http://localhost:4200/assets/vendor.js:8865:9
    at Object.<anonymous> (http://localhost:4200/assets/vendor.js:68364:9)
    at Object.dispatchEvent (http://localhost:4200/assets/vendor.js:68408:24)
    at Object._readyStateChange (http://localhost:4200/assets/vendor.js:68608:14)
    at Object._setResponseBody (http://localhost:4200/assets/vendor.js:68672:14)
    at Object.respond (http://localhost:4200/assets/vendor.js:68693:12)
```

As far as I can tell there is an object which gets parsed twice and thus tries to parse "object ..." to json which fails. Any ideas?

**Comment by taras** [comment]
Try this

```js
this.get('ajax').post('/api/resendEmail', {
        data: JSON.stringify({
          email: email
        })
})
```

**Comment by spruce** [comment]
Thanks for the quick response. But that sadly didn't help.

May I add that I have a mirage route where this is the executed case and where it get's handled like a charm:
```
this.post('/otherEndPoint', function(db, request) { 
    return new Response(401, {}, "not verified");
  });
```

**Comment by taras** [comment]
try this
```js
this.post('/otherEndPoint', function(db, request) { 
    return new Response(401, {}, "not verified");
  });
```

**Comment by spruce** [comment]
What have you changed? and also: this is the case where it's working.

**Comment by taras** [comment]
It's hard to see what the problem is cause it's hidden by the stacktrace, but looks like it's failing because `JSON.parse` is not able to parse your response. You want to check what the response that's coming back. 

In https://github.com/ember-cli/ember-ajax/issues/98#issuecomment-214554552, I wrapped `{}` in `JSON.stringify`to see if that's what needs to be stringified. 

I'm guessing here. If you'd like we can jump on a quick Screenhero session to figure this out.

**Comment by alexlafroscia** [comment]
My guess here is that your server is responding with a String, `"not verified"`, which is then trying to be parsed using `JSON.parse`.  You can see that this is the error thrown when `JSON.parse` encounters a raw string.

<img width="476" alt="screen shot 2016-06-30 at 5 22 09 pm" src="https://cloud.githubusercontent.com/assets/1645881/16508382/32f34e82-3ee7-11e6-8e12-4b8a3962a0ec.png">

If your API is supposed to return a raw string, I would make sure you're setting your headers correctly so that jQuery knows that that is the `content-type`.  We don't call `JSON.parse` anywhere in the library ourselves, that is all within jQuery.

@spruce can you verify if this is actually an `ember-ajax` error or not?  If it's not, then I would like to close this issue!

**Comment by spruce** [comment]
No I think it has nothing todo with ember-ajax but I did think so first and then forgot about it. Thanks for the effort and great library.
